version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 17.3.0
  pre_build:
    commands:
      - echo pre_build
  build:
    commands:
      - echo Build started on `date`
      - npm install
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - '**/*'
  name: manmat-build-$(date +%Y-%m-%d)